// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserInfoRep struct {
	UserId   uint   `json:"userId"`
	UserName string `json:"userName"`
}
