// Code generated by goctl. DO NOT EDIT.
package types

type LoginRep struct {
	Code int    `json:"code"`
	Data string `json:"data"`
	Msg  string `json:"msg"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserInfo struct {
	UserId   uint   `json:"userId"`
	UserName string `json:"userName"`
}

type UserInfoRep struct {
	Code int      `json:"code"`
	Data UserInfo `json:"data"`
	Msg  string   `json:"msg"`
}
